default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: chatwoot_dev

test:
  <<: *default
  database: chatwoot_test

production:
  <<: *default
  database: chatwoot_production